export const ADD_USER_DATA = "ADD_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const ADD_USERS_DATA = "ADD_USERS_DATA";
export const CLEAR_USERS_DATA = "CLEAR_USERS_DATA";
export const ADD_DETAILE_DATA = "ADD_DETAILE_DATA";
export const CLEAR_DETAILE_DATA = "CLEAR_DETAILE_DATA";